# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b-w4hmx_NCm_IjzkH1KWaXl3_4IUMMrV
"""

def telefon_narxi(belgi):
    if   belgi == "iphone":
      return "100$"
    elif belgi == "iphone 2":
      return "200$"
    elif belgi == "iphone 3":
      return "300$"
    elif belgi == "iphone 4":
      return "400$"
    elif belgi == "iphone 5":
      return "500$"
    elif belgi == "iphone 6":
      return "600$"
    elif belgi == "iphone 7":
      return "700$"
    elif belgi =="iphone 8":
      return "800$"
    elif belgi =="iphone 9":
      return "bunaqa iphone yoq"
    elif belgi =="iphone x":
      return "1000$"
    elif belgi == "qimmat ekan sizlarda":
      return "arzonlagan payti chaqiramiz"
    else:
      return "unaqa telefon dokonimizda yoq "



  belgi =input  ("telefon markasini krit ")
  natija=telefon_narxi(belgi)
  print(natija)