# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cOzmg5CVIQutB5ASWI7Bk8AGQV7k-K1J
"""

def kasallik_tashxisi(belgi):
    if   belgi == "isitma":
      return "Parastamol iching "
    elif belgi == "bosh ogrigi ":
      return "bolnol"
    elif belgi == "tish ogrigi":
      return "senipar"
    elif belgi == "oyoq ogrigi":
      return "kupen gel surkang "
    elif belgi == "qol ogrigi":
      return "kupen gel surkang"
    elif belgi == "koz ogrigi":
      return "dam oling "
    elif belgi == "qorn ogrigi":
      return    "espumizan iching"
    elif belgi =="yurak ogrigi":
      return    "kleksan iching"
    elif belgi =="buyrak ogrigi":
      return    "Metrid iching"
    elif belgi =="sogman":
      return    "raxmat keb turing "
    else:
      return "shifokorga murojat qling "



 belgi =input  ("kasallik belgisini kriting ")
 natija=kasallik_tashxisi(belgi)
 print(natija)